{% set version = "2.5-5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-aws
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/aws_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/aws/aws_{{ version }}.tar.gz
  sha256: b27cb2795cb59592d474cfaf49a21657a8878404da4f01c556f7323e953b4c5b

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-awsmethods >=1.0_1
    - r-gsl
    - gsl                        # [win]
  run:
    - r-base
    - r-awsmethods >=1.0_1
    - r-gsl
    - gsl                        # [win]

test:
  commands:
    - $R -e "library('aws')"           # [not win]
    - "\"%R%\" -e \"library('aws')\""  # [win]

about:
  home: http://www.wias-berlin.de/people/polzehl/
  license: GPL-2.0-or-later
  summary: We provide a collection of R-functions implementing adaptive smoothing procedures in 1D, 2D and 3D. This includes the Propagation-Separation Approach to adaptive smoothing as described in "J. Polzehl and V. Spokoiny (2006) <DOI:10.1007/s00440-005-0464-1>", "J. Polzehl and V. Spokoiny (2004) <DOI:10.20347/WIAS.PREPRINT.998>"
    and "J. Polzehl, K. Papafitsoros, K. Tabelow (2018) <DOI:10.20347/WIAS.PREPRINT.2520>", the Intersecting Confidence Intervals (ICI), variational approaches and a non-local means filter.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: aws
# Version: 2.2-1
# Date: 2019-04-23
# Title: Adaptive Weights Smoothing
# Authors@R: c(person("Joerg","Polzehl",role=c("aut","cre"),email="joerg.polzehl@wias-berlin.de"),person("Felix","Anker",role=c("ctb")))
# Author: Joerg Polzehl [aut, cre], Felix Anker [ctb]
# Maintainer: Joerg Polzehl <joerg.polzehl@wias-berlin.de>
# Depends: R (>= 3.4.0), methods, awsMethods (>= 1.0-1), gsl
# Description: We provide a collection of R-functions implementing adaptive smoothing procedures in 1D, 2D and 3D. This includes the Propagation-Separation Approach to adaptive smoothing as described in "J. Polzehl and V. Spokoiny (2006) <DOI:10.1007/s00440-005-0464-1>", "J. Polzehl and V. Spokoiny (2004) <DOI:10.20347/WIAS.PREPRINT.998>" and "J. Polzehl, K. Papafitsoros, K. Tabelow (2018) <DOI:10.20347/WIAS.PREPRINT.2520>", the Intersecting Confidence Intervals (ICI), variational approaches and a non-local means filter.
# License: GPL (>= 2)
# Copyright: This package is Copyright (C) 2005-2018 Weierstrass Institute for Applied Analysis and Stochastics.
# URL: http://www.wias-berlin.de/people/polzehl/
# RoxygenNote: 5.0.1
# NeedsCompilation: yes
# Packaged: 2019-05-07 08:15:05 UTC; polzehl
# Repository: CRAN
# Date/Publication: 2019-05-08 09:20:05 UTC
