travis:
  secure:
    BINSTAR_TOKEN: VnWoPuhbyLdV0Yx5MNbuTg289Q1sFIN/tunFcPflU4A5zY/ufO8jbynGuDnnezRG+SGr86k76FPNnvnu9ts0z7kf6dQuLPOwg8J3ryYt73+JgB60TNJKQQ9rama994PU+8//YsJhvn0HpAH2gNgtOIPLkgfahH/7KmD02pVBfXESJtG3y4TTp0BYAOkoB5Tul+jkm2D1IQDMHShvDesHXwLZUI7RgfNIeMlfuDihq95LdKnCHM57cjn3zVGTJBcavhZ7ARfdjOEuTJY92TcdKE2qWB4aTf64TfN3DZtbdPRYWm5rBDnmB/yB24Mp/xpsGQtDKBf6isQlKyidklD0wGnl3Y/w8crFPcoYR3bAbNSSXAnG2g6Svr93/A82RAeoC9oLc+8A6sucZf7JqpWkckIq+/OI/sy1M5Ft5oat+tQ3xpZtdBjwV3icDlJ2w9oHbTTFkI/w2IQl9aArJAYhFKvol0U6dJzDUmEdFUiVXEMO3MGLeVbs2RZzxBKyd0ufI4KOzVzM9UZvGd/m+tdxDsmaNjygcfDPuOzmgA9HN1KVmlly0EtPK4cY7ASNL6vRvnPVNhaFdbHGtlmJbCae7m0tH83Y+y5NQ3pNEnVOxezp7kKtQWg8XSf4t5nj5dY/1AZZJVtoE63dQDOHzj4lBmBOwlrO53vjbFPyVyk513E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
